In [1]:
# Task 5: BatchNorm and LayerNorm

import numpy as np

# Sample Data (4 samples, 3 features)
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [2,4,6]
], dtype=float)

print("Original Data:\n")
print(X)

# Batch Normalization

batch_mean = np.mean(X, axis=0)
batch_var = np.var(X, axis=0)

batch_norm = (X - batch_mean) / np.sqrt(batch_var + 1e-5)

print("\nBatch Normalization:\n")
print(batch_norm)

# Layer Normalization

layer_mean = np.mean(X, axis=1, keepdims=True)
layer_var = np.var(X, axis=1, keepdims=True)

layer_norm = (X - layer_mean) / np.sqrt(layer_var + 1e-5)

print("\nLayer Normalization:\n")
print(layer_norm)

Original Data:

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [2. 4. 6.]]

Batch Normalization:

[[-1.09108841 -1.27016924 -1.41421199]
 [ 0.21821768  0.11546993  0.        ]
 [ 1.52752378  1.5011091   1.41421199]
 [-0.65465305 -0.34640979  0.        ]]

Layer Normalization:

[[-1.22473569  0.          1.22473569]
 [-1.22473569  0.          1.22473569]
 [-1.22473569  0.          1.22473569]
 [-1.22474258  0.          1.22474258]]
